### ISSUE TITLE
The readmes aren't in sync

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [alanz/vscode-hie-server#1]
Hi
I'm trying to create my own language server so I was trying to use this as a simple example.
I think the instructions are not up to date anymore or something.
https://github.com/alanz/haskell-lsp
Simply running the extension does not create the tmp file as I would expect

https://github.com/alanz/vscode-hie-server/blob/master/vsc-extension-quickstart.md
it says that there is a registerCommand function being invoked but I can't find it anywhere

I'm using the current master

**Comment by alanz** [comment]
That executable has actually rotted, I need to remove it. Your best bet is to use https://github.com/alanz/haskell-ide-engine/tree/lsp

This pulls in `haskell-lsp` and makes use of it, in https://github.com/alanz/haskell-ide-engine/blob/lsp/src/Haskell/Ide/Engine/Transport/LspStdio.hs

**Comment by alanz** [comment]
PS, there is an IRC channel at freenode #haskell-ide-engine

**Comment by alanz** [comment]
See https://github.com/alanz/haskell-lsp/commit/a0953e1dd9ca246c018c49c5ae7aa8355ab4e9fa

And I just realised you need to use the `spec-v3.0` branch

**Comment by Tehnix** [comment]
Closing to clean up stale issues.
