### ISSUE TITLE
haskell-lsp gets wrong cwd

### ISSUE THREAD

**Issue by adamschoenemann** [alanz/vscode-hie-server#109]
Thanks for writing this engine! I'm trying to use haskell-ide-engine along with vscode-hie-server and multiroot workspaces but I'm running into some issues.

I have a large repository containing several Haskell projects and many projects in different languages, so I don't want to just open all folders in a single workspace. I have a `stack.yaml` inhaskell-lsp gets wrong cwd the root and stack will pick this up just fine from nested directories, but `hie-wrapper` does not find it, incorrectly attempting to launch a "plain GHC version".
https://github.com/alanz/vscode-hie-server/issues/109
So I set up a multi-rooted workspace with a folder and edited its settings to use a custom wrapper script, whose job simply is to run `hie-wrapper` with the root of the repo (where `stack.yaml` is located). However, I'm getting weird results, and I think it is because the root is not passed to `haskell-lsp`. Looking at the debug output, I can see that `haskell-lsp` is initialized with the nested folder as root, and not the root I've specified in my custom wrapper. Looking at the source code, this also seems to be the case, since `haskell-lsp` is started directly by the vscode extension with the workspaThanks for writing this engine! I'm trying to use haskell-ide-engine along with vscode-hie-server and multiroot workspaces but I'm running into some issues.

**Comment by adamschoenemann** [comment]
Sort of. It's kind of like this:
```
my-big-project/
- hask-project-1/
- non-hask-project/
- hask-project-2/
- stack.yaml
```
I don't want one huge workspace with all the sub-projects (in reality there are quite a few!), so I created an empty workspace and used "Add folder to workspace" to add `hask-project-2`.
But doing this naively will start `hie-wrapper` in `my-big-project/hask-project-1` where it'll then attempt to use a global ghc installation since it cant pick up the stack.yaml in the parent directory. So I tried to use a wrapper script to make it start in the parent directory, but `haskell-lsp` still gets the child directory as its root. I hope that makes it more clear :)

**Comment by alanz** [comment]
Multi-root workspaces are a new thing in vscode, and not properly supported in hie at the moment.

And if anyone cares deeply about them, I suggest they make a PR on hie, I personally think they are an anti-pattern.

**Comment by adamschoenemann** [comment]
Maybe the real problem is that hie or hie-helper should properly pick up the `stack.yaml` for parent directories, so it can be started in whatever "nested" workspace and still pick up the fact that it's a stack project? In that case, this issue can be closed and we can open a new one in hie. However, `lsp-haskell` would also need to be passed the correct parent directory from this plugin...

For now, I just open the entire directory as a workspace, and although it's a bit annoying it works somewhat reliably.

**Comment by alanz** [comment]
So at the top level you have a stack.yaml which lists the sub-projects as dependencies?

We have that in hie itself, and it results in a hie instance per sub-project. This is the level that the compilation information is made available, we can't stitch together a mega thing with all the sub projects in one.

This is similar to trying to load them all into ghci, we have the same constraints.

**Comment by adamschoenemann** [comment]
Hmm, maybe I'm misunderstanding something, but if I run `hie` or `hie-wrapper` in any of the subdirectories (each have a separate .cabal file) it'll try to use the global installation of ghc (which I don't have). The root directory has a `stack.yaml` which lists the sub-projects in `packages`.

**Comment by alanz** [comment]
To have it work as you expect put a `stack.yaml` in each sub-project, specifying the resolver version at a minimum.

**Comment by adamschoenemann** [comment]
Hmm ok. Stack picks up the `stack.yaml` in the parent directory from any subdirectory, so I guess that's why I expected the same behaviour from `hie`. I'll try to work around it somehow. Thanks for your help!
