### ISSUE TITLE
Multiple instances of HIE run for single project

### ISSUE THREAD

**Issue by kfigiela** [alanz/vscode-hie-server#111]
VSCode is starting multiple instances of HIE for the same project. Since each instance consumes a lots of memory as discussed in https://github.com/haskell/haskell-ide-engine/issues/412 this becomes a problem. Also, duplicated list of symbols appear on newly introduced breadcrumbs causing additional inconvenience.

@dktn noticed that the number of instances that are started depends on number of editor panes that were open when the workspace was loaded. For example: I close all editors, execute "Reload Window" command, one HIE instance is started after window reload. Next, I open more panes (my typical setup is 2 or 3 editors in single window) and there is still one instance.

This is how it should look like:
![image](https://user-images.githubusercontent.com/174118/45084615-0dd4d080-b0ff-11e8-8653-21e92a5210b6.png)
![image](https://user-images.githubusercontent.com/174118/45084598-07465900-b0ff-11e8-92e7-4d0668254638.png)

When I do "Reload Window" (or restart vscode) with more than one pane open duplicate instances are started:
![image](https://user-images.githubusercontent.com/174118/45084526-d8c87e00-b0fe-11e8-8f80-e0e46c4929a0.png)
![image](https://user-images.githubusercontent.com/174118/45084544-df56f580-b0fe-11e8-8b00-85d178da58c0.png)

I also noticed, that there is other way to reproduced this issue with single pane only. The trick is to have some unsaved Haskell file open in inactive tab when workspace is reloaded. An extra HIE instance is opened for each extra unsaved editor.

**Comment by alanz** [comment]
Ok, so it sounds like the extension is not properly working out the project root.
It *is* supposed to launch a separate instance for each sub-project though.

**Comment by kfigiela** [comment]
Sure, I'd expect to have separate HIE for each project. This not the case however, this is the only Haskell project in my workspace.

Regarding that list of tasks, it's that dropdown
![image](https://user-images.githubusercontent.com/174118/45104689-ebf54100-b132-11e8-9b3a-4cde89eda7ae.png)

**Comment by alanz** [comment]
I actually suspect this may be a vscode issue. But will take a look.

**Comment by lorenzo** [comment]
This is how to reproduce:

* open the project
* open 2 or 3 `.hs` files
* close vscode
* open it again and verify in the process list that at least 2 hie were started

**Comment by kfigiela** [comment]
@lorenzo, this does not happen when `.hs` files are open in single pane (unless they are unsaved when window is reloaded). This happens when multiple panes are used and `.hs` files are active tabs in those panes.

**Comment by kfigiela** [comment]
Looks like it's a concurrency bug, made a PR #113 with a fix that seems to work fine.
