### ISSUE TITLE
README and hie-wrapper

### ISSUE THREAD

**Issue by justjoheinz** [alanz/vscode-hie-server#112]
I believe this section is out of date or misguiding:
https://github.com/alanz/vscode-hie-server#hie-wrapper

It seems that the setting has been removed entirely and at least there are issues concerning the use on Mac OS X which report that this setting is no longer supported. 

See #105 

I would submit a PR but I am currently clueless what the desired installation should be.

**Comment by alanz** [comment]
Updated via https://github.com/alanz/vscode-hie-server/commit/a551c65e41758c59e564cfc5c0352d8c7afa4c5b

Is this clearer now?

**Comment by jneira** [comment]
The setting was restored and afaik it works
@justjoheinz feel free to reopen if you have any concern
