### ISSUE TITLE
Undo last change when saving.

### ISSUE THREAD

**Issue by Magicloud** [alanz/vscode-hie-server#116]
Vscode in Ubuntu Bionic. GHC 8.4.3. Necessary tools are all from Stackage. I have disabled all my exts and enabled one by one to test. So I am sure its this one.

Actually 2 problems I see.

1. Sometimes, when I save my work (save, save all, menu, hotkey, etc), it insists undo last change before writing data.

2. Sometimes, especially when it is just a code skeleton, code got messed up when saving, like extra redundant lines.

**Comment by Magicloud** [comment]
Today I did another test. Seems like the first issue was not "undo". It is formatting that does not accept unicode operators.

**Comment by jneira** [comment]
@Magicloud do you continue experiencing this with latest versions of the extension and hie?

**Comment by Magicloud** [comment]
Sorry, I cannot confirm. HIE does not work for me recently.

**Comment by jneira** [comment]
Oh, sorry to hear that, would you have time to open a new issue with the incorrect behaviour?
In the meanwhile i will close this one.

**Comment by Magicloud** [comment]
OK.
