### ISSUE TITLE
hie-server running but not sending any rpc messages to vscode.

### ISSUE THREAD

**Issue by SamDM** [alanz/vscode-hie-server#118]
I have a fresh install of hie using the Arch package on AUR (https://aur.archlinux.org/packages/haskell-ide-engine-git/).

When opening a haskell file, the extension does not seem to do anything. No code completion, no linting, nothing (except for syntax highlighting). Enabling the logs, I see that the hie server is running. The log file reflects the actions I perform in vscode such as moving the cursor, etc.

When I look at the server dump, nothing is sent back to vscode. In neither of the log files is there any indication that something is going wrong. It is only by logging the output using `--vomit` that something pops up:

    hie-8.4.3: user error (Failed to find requested hint files:
      /usr/bin/data/hlint.yaml
    )

Do I need a global installation of hlint to make this work? Why? Shoulnd't it use hlint from stack?

Attached are the 1) my custom hie wrapper to enable the logs, 2) the log, 3) the server dump and 4) the stderr from hie containing information from `--vomit`.

[hie-vscode.sh.txt](https://github.com/alanz/vscode-hie-server/files/2473309/hie-vscode.sh.txt)
[hie.log](https://github.com/alanz/vscode-hie-server/files/2473311/hie.log)
[hie-wire.log](https://github.com/alanz/vscode-hie-server/files/2473312/hie-wire.log)
[hie-stderr.log](https://github.com/alanz/vscode-hie-server/files/2473314/hie-stderr.log)

If I can do anything to help or if any additional info is required, let me know.

**Comment by barrymoo** [comment]
@SamDM I am facing a similar issue. If I simply create a sym link from `hlint.yaml` to that location I can get past that error. The next one I hit is `hie-8.4.3: Could not find $libexecdir/cabal-helper-wrapper`.

**Comment by barrymoo** [comment]
@SamDM I would try this suggestion: https://github.com/haskell/haskell-ide-engine/issues/483#issuecomment-410607007. After copying the `cabal-helper-wrapper` to my `~/.local/bin` it worked fine.

**Comment by jneira** [comment]
Hie no longer use cabal-helper-wrapper, otoh the runtime dependency on the hlint data file is known issue, tracked (and about to be fixed!) in: https://github.com/haskell/haskell-ide-engine/issues/1143
