### ISSUE TITLE
Need to reopen file to update documentation and error reporting

### ISSUE THREAD

**Issue by huylv** [alanz/vscode-hie-server#122]
When writing new code, no error reporting or documentation is updated in realtime. I have to close and reopen the file for them to show up. That also means no more undos/redos. Is it an expected behavior? I'm using Haskell Language Server v0.0.24.

**Comment by Avi-D-coder** [comment]
There are currently a number of cases where hie becomes unresponsive. Unfortunately restarting is often necessary.

**Comment by jneira** [comment]
@huylv do you continue expereincing it with latest versions of the extension and hie?

**Comment by jneira** [comment]
closing this, feel free to reopen or apoen a new one if you continur experiencing the issue
