### ISSUE TITLE
The hover message cannot shows token correctly

### ISSUE THREAD

**Issue by OlingCat** [alanz/vscode-hie-server#123]
The `<$>` should be recognized as a whole token:
![img](https://i.loli.net/2018/11/27/5bfcc9b41eac4.gif)

Same bug for `Char` and `[Char]`:
(The top one from Simple GHC Integration; the middle one from HIE; and the bottom one from Haskelly):
![img](https://i.loli.net/2018/11/27/5bfcca371d770.gif)

**Comment by halhenke** [comment]
I cant reproduce this bug. Its been a while since i looked at this plugin and the underlying hover/hint implementation seems to have changed quite a bit - might try to change the showTypes on hover implementation to reflect some other behaviour which has become a bit inconsistent

**Comment by jneira** [comment]
@OlingCat it seems it could be fixed, please try again with latest versions of the extension and hie and reopen if you continue experiencing it
