### ISSUE TITLE
Ask user to download HIE if not found

### ISSUE THREAD

**Issue by Tehnix** [alanz/vscode-hie-server#125]
I completely missed that [HIE now has binaries for macOS](https://github.com/haskell/haskell-ide-engine/commit/a7b120f96d53d0fbf97d93a07559e4df28adebff), which (for me) means that we can finally get some sleak UX for automatically fetching the needed HIE binaries. I'm pretty sure there's some pre-built for Linux also, but can't seem to find them atm.

The flow could go something like:
```
           Try to detect if HIE is on path
                         |
                         v
   If not: ask user to download HIE. If it is: carry on as usual
                         |
                         v
   The user is presented with the dialog and has the option of
   "Download HIE", "Dismiss", "Permanently Dismiss"
                         |
                         V
   If "Download HIE" is chosen, we fetch HIE and put it on path
``` 

I think this will help **majorly** w.r.t. adoption, since now people can just install the extension and get running almost immediately, without spending an hour (almost literally) compiling the ~6 different HIE versions.

**Comment by expipiplus1** [comment]
Looks as though this is waiting for hie to be on hackage/stackage: https://github.com/alanz/vscode-hie-server/blob/master/src/extension.ts#L75

**Comment by jneira** [comment]
In addition to upload to hackage/[stackage](https://github.com/haskell/haskell-ide-engine/issues/328) we want to add precompiled binaries: https://github.com/haskell/haskell-ide-engine/issues/1068
There is a similar issue in hie: https://github.com/haskell/haskell-ide-engine/issues/1383 so i will close this one if you dont mind (reopen if it is not the case)
