### ISSUE TITLE
Support for pre-built HIE binaries?

### ISSUE THREAD

**Issue by maxrothman** [alanz/vscode-hie-server#127]
[HIE's installation instructions for Mac](https://github.com/haskell/haskell-ide-engine#installation-on-macos) read:

> ### Installation on macOS
> Download the pre-built binaries from the releases page, and copy/symlink them into /usr/local/bin (or somewhere else in your $PATH)

Yet when I do so, I get the following error in the "Haskell (HIE)" output panel in VSCode:
```
hie-8.2.2: user error (Failed to find requested hint files:
  /path/to/hie/bins/data/hlint.yaml
)
```

I notice HIE's instructions also conflict with vscode-hie-server's:

> The language client requires you to manually install the HIE language server,
> ```
> $ git clone https://github.com/haskell/haskell-ide-engine --recursive
> $ cd haskell-ide-engine && make build-all
> ```
> Alternatively you can just stack install, but make build-all will give you the best setup.

It appears that HIE is trying to move to pre-built binaries to improve the install and update experience, it'd be nice is vscode-hie-server supported them too.

**Comment by alanz** [comment]
It turned out not to be possible to pre-build macos binaries, so this has now been deprecated. For now.

**Comment by maxrothman** [comment]
It looks like HIE has removed all mentions of pre-built binaries from their documentation.
