### ISSUE TITLE
cabal-helper-wrapper "print-build-platform" (exit 1): failed.

### ISSUE THREAD

**Issue by srcdes** [alanz/vscode-hie-server#128]
When i open a `.hs` file in vscode, an error occurred following:

```
Got error while processing diagnostics: readCreateProcess: /Users/foo/dev/study/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.0/8.6.3/bin/cabal-helper-wrapper "print-build-platform" (exit 1): failed
```

```bash
$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.6.3
```

MacOS : 10.14.2
vscode : 1.30.1(1.30.1)

**Comment by alanz** [comment]
Does `/Users/foo/dev/study/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.0/8.6.3/bin/cabal-helper-wrapper` exist?

After installing hie, you have to leave the directory intact that it was installed from.

**Comment by ghdbox** [comment]
Yep, That file exists.

```bash
$ ls -l /Users/foo/dev/study/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.0/8.6.3/bin/cabal-helper-wrapper
.rwxr-xr-x      1 6.8Mi foo staff 2018-12-29 18:53 /Users/foo/dev/study/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.0/8.6.3/bin/cabal-helper-wrapper
```

**Comment by alanz** [comment]
And what happens if you run

```
/Users/foo/dev/study/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.0/8.6.3/bin/cabal-helper-wrapper print-build-platform
```

**Comment by ghdbox** [comment]
The result:

```bash
$ /Users/foo/dev/study/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.0/8.6.3/bin/cabal-helper-wrapper print-build-platform
cabal-helper-wrapper: dieVerbatim: user error (cabal-helper-wrapper: The program 'ghc' version >=7.0.1 is required but it
could not be found.
)
```

Hmm, do i need to expose `ghc` command on my bash environment? I am using `stack ghc` instead of `ghc`:

```bash
$ ghc --version
zsh: command not found: ghc

$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.6.3
```

**Comment by alanz** [comment]
It looks like the wrapper is also expecting a system ghc to be installed. 

What I do is just symlink the stack one in to a location on the path somewhere, but in the meantime this is a bug, I will look into it.

**Comment by alanz** [comment]
This line is the problem.

https://github.com/alanz/cabal-helper/blob/cabal-new-legacy/src/CabalHelper/Compiletime/Wrapper.hs#L162

**Comment by ghdbox** [comment]
Oh, you are right. Thanks. I appended a path for `ghc` into my `.zshrc` file following. And the error was gone. Is this a right way to fix this error, especially the path for `ghc` ?:

```bash
export PATH=~/.stack/programs/x86_64-osx/ghc-8.6.3/bin:$PATH
```

**Comment by alanz** [comment]
you can also use

```bash
export PATH=$(stack path --compiler-exe):$PATH
```

**Comment by ghdbox** [comment]
I assume `--compiler-exe` should be `--compiler-bin`... :)

```bash
$ stack path --compiler-exe
/Users/foo/.stack/programs/x86_64-osx/ghc-8.6.3/bin/ghc

$  stack path --compiler-bin
/Users/foo/.stack/programs/x86_64-osx/ghc-8.6.3/bin
```

**Comment by FledgeXu** [comment]
Hey Guys,I have the same problem.
```
  ls -l /Users/fledge/Develpment/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.5/8.6.3/bin/cabal-helper-wrapper
```
```
-rwxr-xr-x  1 fledge  staff  7089880 Feb 21 20:41 /Users/fledge/Develpment/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.5/8.6.3/bin/cabal-helper-wrapper
```
When I run the cabal-helper-wapper, It shows:
```
cabal-helper-wrapper: dieVerbatim: user error (cabal-helper-wrapper: The program 'ghc' version >=7.0.1 is required but it
could not be found.
)
```
what should I do?

Should I install ghc above 7.0 by stack?

**Comment by jinbeomhong** [comment]
@FledgeXu You should add `ghc` command to `PATH` environment variable of your shell.

**Comment by FledgeXu** [comment]
@jinbeomhong It works! Thank you for your help.

**Comment by krikchaip** [comment]
> I assume `--compiler-exe` should be `--compiler-bin`... :)
> 
> ```shell
> $ stack path --compiler-exe
> /Users/foo/.stack/programs/x86_64-osx/ghc-8.6.3/bin/ghc
> 
> $ stack path --compiler-bin
> /Users/foo/.stack/programs/x86_64-osx/ghc-8.6.3/bin
> ```

Hi there,
I already did this. but the error still occurs 😕

<img width="960" alt="screen shot 2562-02-25 at 17 36 50" src="https://user-images.githubusercontent.com/23186625/53331639-fb0bbd80-3923-11e9-8e0e-416b4fc28b96.png">

<img width="1194" alt="screen shot 2562-02-25 at 17 38 23" src="https://user-images.githubusercontent.com/23186625/53331755-3a3a0e80-3924-11e9-823d-49cf4861a1bf.png">

<img width="1194" alt="screen shot 2562-02-25 at 17 47 15" src="https://user-images.githubusercontent.com/23186625/53332258-70c45900-3925-11e9-86ba-8d405ce692c1.png">

```zsh
$ haskell-ide-engine/.stack-work/install/x86_64-osx/lts-12.26/8.4.4/bin/cabal-helper-wrapper print-build-platform
x86_64-osx
```

```zsh
$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.4.4
```

**Comment by KillyMXI** [comment]
I got this on Windows 10.
I would love to not depend on workarounds for this issue.

**Comment by luochen1990** [comment]
Following is my workaround (as a summarize of @alanz and @jinbeomhong 's above comment):

add `export PATH="$(stack path --compiler-bin):$PATH"` to rc file, so that the command `ghc` works, and this issue gone.

**Comment by Rizary** [comment]
Hi... I got the following error when trying to run `vscode-hie-server` extension on my WSL.
```
Got error while processing diagnostics: readCreateProcess: /nix/store/1i3fyx4wywvkzz1fcji6zysshvxvx5ja-cabal-helper-0.9.0.0/bin/cabal-helper-wrapper "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" "/home/rizary/Haskell/alltuts/fp-course" "/home/rizary/Haskell/alltuts/fp-course/dist" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output" (exit 1): failed
```
I am using [`all-hies`](https://github.com/Infinisil/all-hies) and hvr:ppa for my cabal and ghc/ghcjs binary.

One thing that I noticed here is that cabal-helper put this ` "v1-style" "/home/rizary/Haskell/alltuts/fp-course" "/home/rizary/Haskell/alltuts/fp-course/dist" ` argument automatically whereas I'm using v2-style and the `dist` folder is not existed (dist-newstyle is).

So I try to run it manually and change it into:
```"--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v2-style" "/home/rizary/Haskell/alltuts/fp-course" "/home/rizary/Haskell/alltuts/fp-course/dist-newstyle" "package-db-st
ack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-op
tions" "ghc-options" "source-dirs" "entrypoints" "needs-build-output"``` 

and get the following output:

```
cabal-helper-wrapper: UnitId 'package-db-stack' not found in plan.json, available local units:
  course-0.1.4-in place
  course-0.1.4-in place-tasty
```
Is this output already what is intended by `cabal-helper-wrapper`? Or how can I have `plan.json`?

**Comment by Infinisil** [comment]
I think as of now HIE doesn't work well with the new-style commands (https://github.com/haskell/haskell-ide-engine/pull/962 is related). For my development I'm therefore still using the old-style commands.

**Comment by jneira** [comment]
hie not longer uses cabal-helper-wrapper and it is able to start using stack if there is no ghc on path so i think this should be fixed with latest versions of hie and the extension: @srcdes @FledgeXu @krikchaip @KillyMXI @Rizary @luochen1990  feel free to reopen if it is not the case
