### ISSUE TITLE
Does this extension support building stack projects and putting the results in the Problems window?

### ISSUE THREAD

**Issue by spacekitteh** [alanz/vscode-hie-server#132]
As in, a "build" button a la Haskelly.

Alternatively: Can `hie` be used as an output parser for vscode tasks?

**Comment by alanz** [comment]
This extension operates as a language server, so as you edit a file the modified file is processed by hie to generate diagnostics.

**Comment by jneira** [comment]
@spacekitteh feel free to reopen if you feel your question was not answered
