### ISSUE TITLE
Code actions of kind 'quickfix 'requested but returned code action is of kind 'refactor'. Code action will be dropped.

### ISSUE THREAD

**Issue by spacekitteh** [alanz/vscode-hie-server#133]

**Comment by alanz** [comment]
I think this has been addressed by https://github.com/haskell/haskell-ide-engine/pull/1082

Please confirm

**Comment by jneira** [comment]
This was fixed by https://github.com/haskell/haskell-ide-engine/pull/1537
@spacekitteh feel free to reopen if this is reproduced with latest versions of hie and the extension
