### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Teslamandev** [alanz/vscode-hie-server#137]
[alanz.vscode-hie-server-unresponsive.cpuprofile.txt](https://github.com/alanz/vscode-hie-server/files/2905653/alanz.vscode-hie-server-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-hie-server`
- Extension Version: `0.0.24`
- OS Version: `Linux x64 4.19.24-1-MANJARO`
- VSCode version: `1.31.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

Hi, i periodically faced with the problem of high cpu loading. It happens suddenly when i try to start typing something. My computer freezes and i can't do anything.

**Comment by chrismwendt** [comment]
![image](https://user-images.githubusercontent.com/1387653/62275148-91c23600-b3fe-11e9-8258-7f5f5b22f37e.png)

It looks like 20+ seconds were spent loading files 😱

I bet bundling this extension into 1 JavaScript file (vs 2000 separate files, which is what it is right now) https://github.com/alanz/vscode-hie-server/pull/159 will solve this.

**Comment by alanz** [comment]
Should this have been closed? I do not see the connection.

**Comment by chrismwendt** [comment]
I think it was taking a long time to load the extension because there were a large number of files. After bundling into 1 JS file, it is much faster.
