### ISSUE TITLE
"Go to Symbol in Workspace" (Ctrl+T) not working

### ISSUE THREAD

**Issue by afcowie** [alanz/vscode-hie-server#138]
I'm reasonably sure I followed the instructions well; most other features of **hie** are working great. But for some reason symbol lookup from the `Go` menu under `Go to Symbol in Workspace (Ctrl+T)` isn't populated with any symbols.

Interestingly the `Outline` feature in the file Explorer _is_ populated, and `Go to Symbol in File (Ctrl+Shift+O)` _does_ work. Huh! But whatever the action is that populates individual files' symbols (sic) into a global (that is, workspace) list of symbols seems to be missing.

Any suggestions?

There weren't any references to this in the _README_, so I thought I would file an issue. If it *is* something that (is supposed to) work and merely needs FAQ or instructions added, I'll send in a pull request adding it if you want.

AfC

**Comment by afcowie** [comment]
(incorrectly reported against **haskell-ide-engine** in https://github.com/haskell/haskell-ide-engine/issues/1123; moved issue here)

**Comment by chrismwendt** [comment]
I think this needs to be implemented in HIE, not in the VS Code extension.

Both features (the symbol outline and "Go to Symbol in Workspace") come from LSP:

- https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol handled at https://github.com/chrismwendt/haskell-ide-engine/blob/a67490b656a001806c09436acdfce80bf4903f57/src/Haskell/Ide/Engine/Transport/LspStdio.hs#L727
- https://microsoft.github.io/language-server-protocol/specification#workspace_symbol `ReqWorkspaceSymbols` is not yet handled in https://github.com/chrismwendt/haskell-ide-engine/blob/a67490b656a001806c09436acdfce80bf4903f57/src/Haskell/Ide/Engine/Transport/LspStdio.hs#L361

**Comment by jneira** [comment]
It seems it should be implemented in hie so i will reopen the original one and close this one
