### ISSUE TITLE
'vscode.previewHtml' deprecated

### ISSUE THREAD

**Issue by Kitanotori** [alanz/vscode-hie-server#141]
Filing an issue as commanded by vscode:

> Extension 'alanz.vscode-hie-server' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

vscode version 1.32.3

**Comment by EdAllonby** [comment]
Also noticed this warning today. Had a pop at fixing it over at #142.
