### ISSUE TITLE
problems reported in OUTPUT are not updated

### ISSUE THREAD

**Issue by andrewufrank** [alanz/vscode-hie-server#143]
I use VS code 1.32 with hie-server 0.0.25 and hie 0.7.0.0. 
I observe that the the errors and problems reported are oftentime out of sync/not update. If I run `stack build` in the terminal I get errors which are not shown in PROBLEMS and there are errors listed which are corrected. Is there a way to force the synchronization? How to restart the process to detect and show the current problems?
thank you for the integration!

**Comment by andrewufrank** [comment]
It would be very helpful if there were a method to (1) restart HIE from `vs code` or (2) find the pid of HIE to kill it - the one dealing with this thread (not `pidof` which gives all HIE threads running)

**Comment by jneira** [comment]
The handling of temporal files used by the extension (probably the cause of the issue) has changed a lot and maybe it fixed the issue, @andrewufrank could you try with latest versions of hie and the extension? feel free to reopen if you continue experiencing it

(The feature of restart hie is tracked in #46)
