### ISSUE TITLE
Optional special rendering of Haskell keywords

### ISSUE THREAD

**Issue by LeanderK** [alanz/vscode-hie-server#15]
I always wanted to do that 🙂
I would like vscode to render forall as ∀, \ as λ etc. without actually writing unicode. I don't know if it's feasable, but if it's not much work, i would try to find an evening dedicated to solving this problem. I would make it optional though.

**Comment by Tehnix** [comment]
I think this plugin should do what you want https://marketplace.visualstudio.com/items?itemName=siegebell.prettify-symbols-mode :) 

Let me know if not, and we can figure out where it might be appropriate to do this at.
