### ISSUE TITLE
Apply bundler to the extension

### ISSUE THREAD

**Issue by alanz** [alanz/vscode-hie-server#151]
`vsce package` says

```
This extension consists of 2753 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension
```

**Comment by halhenke** [comment]
Hey - I'm happy to take this - have something working with parceljs but for some reason it only packages properly when vsce is used with yarn (`vsce package --yarn`). Will try to get something working with npm if possible but otherwise will make a PR.
