### ISSUE TITLE
languageServerHaskell.useCustomHieWrapperPath option don't work properly with workspaceFolder variable on Windows

### ISSUE THREAD

**Issue by QuietJoon** [alanz/vscode-hie-server#162]
When I set `languageServerHaskell.useCustomHieWrapperPath` with absolute path or `${HOME}` variable, it works.
However, with `${workspaceFolder}`, it doesn't parse the path properly when running VSCode on Windows but parses the path as *unix way

Works well:

* `"languageServerHaskell.useCustomHieWrapperPath": "${HOME}/hie.bat"`
* "languageServerHaskell.useCustomHieWrapperPath": "${HOME}\\hie.bat"
* "languageServerHaskell.useCustomHieWrapperPath": "A:\\ABSOLUTEPATH\\hie.bat"

Not works:

* "languageServerHaskell.useCustomHieWrapperPath": "${workspaceFolder}/hie.bat"
  * Error message: `Launching server using command /t:/WORKSPACEFOLDER/hie.bat failed.`
* "languageServerHaskell.useCustomHieWrapperPath": "${workspaceFolder}\\hie.bat"
  * Error message: `Launching server using command /t:/WORKSPACEFOLDER\hie.bat failed.`

**Comment by jneira** [comment]
The wrapper extension settings has been removed, feel free to reopen and edit or open a new one if you reproduce it with other existing extension options
