### ISSUE TITLE
"The Haskell HIE (haskell) server crashed 5 times in the last 3 minutes. The server will not be restarted."

### ISSUE THREAD

**Issue by ConnorJL** [alanz/vscode-hie-server#164]
I'm running VSCode on Xubuntu and installed HIE using nix (I can't build HIE because it takes more hard drive space than I have on my machine). The hie and hie-wrapper binaries are callable just fine through a bash shell and start without an issue. But every time I open a haskell file I get the error "The Haskell HIE (haskell) server crashed 5 times in the last 3 minutes. The server will not be restarted."

I then tried everything I could think of, including a custom wrapper to create a log, which contains the following: [link](https://pastebin.com/26eWA6B3)

Any help would be greatly appreciated!

**Comment by YouWillBe** [comment]
https://github.com/haskell/haskell-ide-engine/issues/1470

**Comment by ogkloo** [comment]
I had this happen several times, along with a host of other problems, that I resolved by running `code <project_dir>` rather than just `code` from an arbitrary directory. It seems hard to come to the conclusion that this is the best way to do this, but after that it works just fine.

**Comment by YouWillBe** [comment]
> I had this happen several times, along with a host of other problems, that I resolved by running `code <project_dir>` rather than just `code` from an arbitrary directory. It seems hard to come to the conclusion that this is the best way to do this, but after that it works just fine.

Still can not start up. I gave up...

**Comment by fendor** [comment]
@ConnorJL may I ask, do you have a ghc installed or are you using only stack?

**Comment by ConnorJL** [comment]
@fendor I have ghc installed (and on PATH) on this machine yes.

**Comment by fendor** [comment]
@ConnorJL I actually would suggest trying the latest master. A lot has changed since August.

**Comment by ConnorJL** [comment]
For unrelated reasons, I have nuked the system this wasn't working on. HIE works fine on my new system. Sorry for not being too helpful in tracking down bugs, and thank you for your work on this tool!

**Comment by fendor** [comment]
@ConnorJL No worries, we have more than enough bugs left, you will be helpful in another :)
