### ISSUE TITLE
hie-server doesn't start up anymore. Win10

### ISSUE THREAD

**Issue by XanderDJ** [alanz/vscode-hie-server#177]
First of all. I have checked that both hie and hie wrapper are in the path. I also have put the path directly in the settings but this didn't work. In output all i see is. I'm using visual studio code in windows 10.
`
[Error - 21:04:56] Connection to server is erroring. Shutting down server.  
[Error - 21:04:56] Connection to server is erroring. Shutting down server.  
[Error - 21:04:56] Connection to server is erroring. Shutting down server.  
[Error - 21:04:56] Connection to server is erroring. Shutting down server.  
`
I don't see a log anywhere so I'm not sure to where to find a more detailed description of the problem. When I first installed the haskell-language-server extension everything worked fine. It stopped working when I closed vscode the first time.

**Comment by jneira** [comment]
Hi! A quick check could be run in a console: 
* `hie --version`: to get the version (you can share here the output)
* `hie --lsp --debug`: to check if hie can be executed out of vscode (you can exit with ctrl+c)
```console
PS D:\dev\ws\haskell\haskell-ide-engine> hie --version
Version 0.13.0.0 x86_64 ghc-8.6.5
PS D:\dev\ws\haskell\haskell-ide-engine> hie --debug --lsp
2019-11-22 21:37:29.0634397 [ThreadId 3] - Using stack GHC version
2019-11-22 21:37:46.2245753 [ThreadId 3] - Run entered for HIE(hie.exe) Version 0.13.0.0 x86_64 ghc-8.6.5
2019-11-22 21:37:46.2401961 [ThreadId 3] - Current directory:D:\dev\ws\haskell\haskell-ide-engine
2019-11-22 21:37:46.2401961 [ThreadId 3] - args:["--debug","--lsp"]
2019-11-22 21:37:46.2714806 [ThreadId 3] -


haskell-lsp:Starting up server ...
```

**Comment by YouWillBe** [comment]
https://github.com/haskell/haskell-ide-engine/issues/1470

**Comment by XanderDJ** [comment]
It randomly works and doesn't work at this point. I get the same messages as YouWillBe.
