### ISSUE TITLE
Improve README description

### ISSUE THREAD

**Issue by AMDphreak** [alanz/vscode-hie-server#178]
The Description of Haskell Language Server in the VSCode Extensions is incredibly useless. What _IS_ Haskell Language Server?

![image](https://user-images.githubusercontent.com/1058978/69847938-2ff3ca80-123e-11ea-81fd-f790d6bb4dc9.png)

![image](https://user-images.githubusercontent.com/1058978/69847772-a93eed80-123d-11ea-8f7e-451a4ca7b11e.png)

You don't bother explaining a damn thing about what it brings to the table for a Haskell user. The "Details" page is a never-ending list of terms that simply refer to each other, creating a cyclic dependency. You need to define this in terms that a potential USER would understand, not just repeat "Haskell Language Server" until you're blue in the face. Jesus Christ none of these damn programming projects has a clue how idiotic their descriptions are.

**Comment by expipiplus1** [comment]
IMO, the "Features" section does a good job of listing what this program provides for Haskell users. Perhaps this section could be moved to above the "Requirements" to make it a little more prominent. 

I suppose that some of the jargon used in the description could be made into hyperlinks to more resources to help explain.

**Comment by nponeccop** [comment]
We can take inspiration from other languages having good descriptions, e.g. the Rust page:

https://marketplace.visualstudio.com/items?itemName=rust-lang.rust

I think we can draft it using an *.md file and let Alan put it to the home page when it's ready.

**Comment by flip111** [comment]
@AMDphreak can you send a pull request to put information similar to the first paragraph of https://marketplace.visualstudio.com/items?itemName=rust-lang.rust under the first paragraph of [readme](https://github.com/alanz/vscode-hie-server/blob/master/README.md)
