### ISSUE TITLE
Hlint hints cannot be applied

### ISSUE THREAD

**Issue by patrickaldis** [alanz/vscode-hie-server#182]
Using latest version of the extension. HIE version 0.14.0.0
I'm finding that all hints displayed by hlint give the appropriate information, but then all display the message 'no quick fixes available'. E.g:
![Screenshot from 2019-12-23 15-39-00](https://user-images.githubusercontent.com/46719614/71366666-96001300-259a-11ea-9109-8e9c27ad84c3.png)

**Comment by jneira** [comment]
Maybe you are already aware but, as temporary workaround, you can apply the refactor clicking on the lightbulb that appears when you set the cursor in the expression

**Comment by patrickaldis** [comment]
Ah no, I didn't realise this. Thanks very much, I'll make sure to use that from now on.
Is the intention to implement it in the tooltip eventually?

**Comment by jneira** [comment]
Sorry for the late response, the idea is they should be there too, yeah.

**Comment by alanz** [comment]
I would say that this is a classification issue, where we no longer comply with the expectations in vscode. hie *is* generating quick fixes, vscode just no longer displays them in the expected place.

**Comment by jneira** [comment]
I feel that activate the quickfix in the hlint suggestion is the more natural way to apply it.  
Anyway, i've opened an issue upstream: https://github.com/haskell/haskell-ide-engine/issues/1524

**Comment by jneira** [comment]
@patrickaldis hi! actual hie master version already has the @alanz fix to see hlint refactor as a quickfix. You can try it pulling last version of hie and building it.

So i think we close this.
