### ISSUE TITLE
Multiline Problems

### ISSUE THREAD

**Issue by patrickaldis** [alanz/vscode-hie-server#183]
Wondering why the hlint errors are displayed as multiline in the 'Problems' section
![Screenshot from 2019-12-23 15-52-21](https://user-images.githubusercontent.com/46719614/71367195-40c50100-259c-11ea-8e92-9e7f1eb9ce80.png)
Would this not be better in a single line?

**Comment by alanz** [comment]
It's formatted that way so you can visually see the differences between the two options, which makes more sense when it is a big complex change.

**Comment by patrickaldis** [comment]
Ah thanks. I understand.
