### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by eo1989** [alanz/vscode-hie-server#187]
- Issue Type: `Bug`
- Extension Name: `vscode-hie-server`
- Extension Version: `0.0.32`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jneira** [comment]
@eo1989 If the issue was the same as #186 (`invalid option --lsp`) the just released version `0.34` of the extension should fix the issue

**Comment by jneira** [comment]
@alanz i think we can close this one (as always @eo1989  could reopen it if version `0.34` does not fix the issue)
