### ISSUE TITLE
Windows 10, The Haskell HIE (...) server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by JorisBlanken** [alanz/vscode-hie-server#189]
I have started using this extension recently and it has worked fine.
However, now whenever I open a haskell file in vscode I get the following error:

>The Haskell HIE (Desktop) server crashed 5 times in the last 3 minutes. The server will not be restarted.

I have tried manually installing vscode-hie-server from master, but to no avail.
It looks like this issue has been experienced by other users, but none that I could find use Windows nor were there any with applicable solutions.

Operating system:
Windows 10
Version 1903 (OS Build 18362.535)

Visual Studio Code:
Version 1.41.1 (system setup)
Commit: 2607a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

HIE:
```
hie --version
Version 1.0.0.0, Git revision b7ce8b8f2fc4a071db2119516aa1dcffc577dca0 (3541 commits) x86_64 ghc-8.6.5
```

GHC:
```
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.1
```

**Comment by jneira** [comment]
Hi, you should be using the version 0.32 of the vscode extension. The version `0.33` is already available and it has an option to avoid the error:
`"languageServerHaskell.noLspParam": true`

**Comment by JorisBlanken** [comment]
> ~Hi, you should be using the version `0.32` of the vscode extension. The version `0.33` is already available and it has an option to avoid the error: `"languageServerHaskell.noLspParam": true`~
> 
> @JorisBlanken A new version of the extension `0.34` has been released and it should fix the issue without setting any option.

I updated to `0.34` and the extension no longer crashes.
Awesome work!

**Comment by vladi2703** [comment]
I am with the latest version of the extension and still get the same message

**Comment by jneira** [comment]
@vladi2703 hi, thanks for the report, that message is the generic one in front of whatever error which makes the lsp server (haskell-language-server in our case) crash (or not found, etc)
could you share your lsp logs to try to identify the root cause? You can check how to do it here: https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems
