### ISSUE TITLE
difficulty starting with multi-module project

### ISSUE THREAD

**Issue by shmish111** [alanz/vscode-hie-server#197]
I am trying to use this plugin with https://github.com/input-output-hk/plutus which is a stack project with multiple sub-projects. I used to have it working but now I'm getting the following:
```
Error parsing targets: No local directories found as children of .
hie-8.0: readCreateProcess: stack "build" "--only-configure" "." (exit 1): failed
```
however it does appear that hie is running (although nothing is working in vscode):
```
➜  HUnit git:(292985320) ✗ ps -ef | grep hie
  501 57115 56255   0  4:36pm ??         0:00.03 /Users/davidsmith/.local/bin/hie-wrapper --lsp -d --vomit
  501 57124 57115   0  4:36pm ??         0:00.44 /Users/davidsmith/.local/bin/hie-8.0 --lsp -d --vomit
```
It looks like the command `stack build --only-configure .` is being run from the directory that contains the source file I am looking at. This fails if I try it from my shell but succeeds if I remove the `.`

```
➜   stack build --only-configure .
Error parsing targets: No local directories found as children of .
➜   stack build --only-configure
➜  echo $?
0
```

**Comment by fendor** [comment]
What kind of hie version is that? It looks like `8.0`? Any idea why `stack build --only-configure .` fails?

**Comment by shmish111** [comment]
I just installed latest `master` `hie` with stack and looking at the VSCode setup it should be using that. I get the following from my terminal:
```
➜   hie --version
Version 1.0.0.0, Git revision f954497a3484ee657b509522c776856ce3f6cc76 (dirty) (3658 commits) x86_64 ghc-8.6.4
```

**Comment by shmish111** [comment]
agh, this was a mistake in my stack.yaml, sorry please ignore the issue

**Comment by fendor** [comment]
No worries, it happens :)
