### ISSUE TITLE
Go To Definition opens a weird tab

### ISSUE THREAD

**Issue by AlexeyRaga** [alanz/vscode-hie-server#2]
When I click `F12` (or `Go To Definition` in a menu) it indeed opens the definition, but in a new tab with a weird title:

![image](https://user-images.githubusercontent.com/1394391/28968849-5a8426e2-7965-11e7-86a1-46f04e95ef17.png)

It would be great if it was opening the real file instead.

**Comment by wz1000** [comment]
@AlexeyRaga this is a bug in HIE. Can you report it in the main HIE repo, along with steps to reproduce if possible?

Sorry, I didn't see this issue until today.

**Comment by AlexeyRaga** [comment]
Reported here: https://github.com/alanz/vscode-hie-server
