### ISSUE TITLE
Getting a warning/suggestion about using hie-wrapper.

### ISSUE THREAD

**Issue by flip111** [alanz/vscode-hie-server#200]
I'm getting this suggestion `Mismatching GHC versions: Stack project is 8.2.2, HIE is 8.6.5
You may want to use hie-wrapper. Check the README for more information`

`hie-wrapper.exe` is in PATH

Even though i don't want to use a custom wrapper [this section](https://github.com/alanz/vscode-hie-server#custom-wrapper) talks about a configuration options `useHieWrapper` which i don't see in the configuration of the extension.

I don't understand why the extension doesn't pick up on hie-wrapper and uses it.

**Comment by fendor** [comment]
Can you post the logs of hie-wrapper? It should be enough to invoke `hie-wrapper --debug` in the root of your project to give us some insight

**Comment by flip111** [comment]
[hie-wrapper_log.txt](https://github.com/alanz/vscode-hie-server/files/4155210/hie-wrapper_log.txt)

**Comment by fendor** [comment]
Well, the message is wrong but the behaviour is correct (or at least in our definition of "correct", not objectively). Stack the project is currently compiled with a snapshot that uses `ghc-8.2.2`. We are not supporting a ghc version that old. However, hie-wrapper attempts to load the project with the most generic hie version we have, which is `hie` but it happens to be version `8.6.5` and, thus, project fails to laod.

**Comment by flip111** [comment]
Is there anything that can be done about this?

**Comment by fendor** [comment]
Use cabal to build the stack project. IIRC, that worked out ok.

**Comment by flip111** [comment]
Can older GHC versions be supported by vscode-hie-server?

The readme could mention which ghc versions are supported at the moment.

This message `Mismatching GHC versions: Stack project is 8.2.2, HIE is 8.6.5 You may want to use hie-wrapper. Check the README for more information` could change depending if it found an unsupported GHC version.

**Comment by fendor** [comment]
We are not compiling this information into an hie executable since this could be outdated as well.
`vscode-hie-server` can not, but hie *could*. If you feel up to the challenge, you could try to add support for `ghc 8.2.2` but there are multiple non-trivial reasons for the support stop. The main reason being that it hogs down the development speed and increases time needed to support multiple versions. HIE is very much under heavy development, and we need to move forward. Moreover, hie is going to be deprecated in favour of https://github.com/haskell/haskell-language-server/ for more confusion :)
See https://github.com/haskell/haskell-ide-engine/#integration-with-ghcide-the-new-haskell-language-server for some more info

**Comment by flip111** [comment]
I also don't feel like adding support for older versions of GHC in haskell-ide-engine. Perhaps i will do it some time in the new haskell-language-server after it matured a bit more.

But this issue is on the vscode-hie-server repo, is it ok to open a pull request to indicate which GHC versions are supported? From `stack ./install.hs help` this seems to be `8.4` and `8.6`.

What situation does `hie-wrapper` cover then actually? Is it so that using hie directly is doing for project usings ghc 8.6 and that `hie-wrapper` is invoked for projects using ghc 8.4 ??

**Comment by fendor** [comment]
> But this issue is on the vscode-hie-server repo, is it ok to open a pull request to indicate which GHC versions are supported 

yes that would be very welcome! On linux, ghc 8.8 is supported as well.

> What situation does hie-wrapper cover then actually? Is it so that using hie directly is doing for project usings ghc 8.6 and that hie-wrapper is invoked for projects using ghc 8.4 ??

when you have multiple stack projects with different ghc versions that the correct version of hie is launched.

**Comment by jneira** [comment]
@flip111 could we close this one? The README was updated and not sure if something is needed to be done in this repo

**Comment by flip111** [comment]
Sure
