### ISSUE TITLE
hie-wrapper needs GHC but this is not required

### ISSUE THREAD

**Issue by flip111** [alanz/vscode-hie-server#202]
```
hie-wrapper: dieVerbatim: user error (hie-wrapper: The program 'ghc' version >=7.0.1 is required but it could not be found.)
```

It's not required by the readme to have GHC in path (if i didn't skip over this information). I use stack so ghc is somewhere installed in the stack internal directories. Not sure what the best approach is to make GHC available.

In my case ghc is located at `C:\Users\flip111\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.2\bin`, i'm not sure if i'm suppose to use this GHC directly.

**Comment by flip111** [comment]
Maybe hie-wrapper can check if stack is installed and invoke ghc through `stack exec -- ghc` instead ??

**Comment by flip111** [comment]
Tried bringing this ghc version into path but got
```
Warning: Unknown/unsupported 'ghc' version detected (Cabal 2.4.1.0 supports 'ghc' version < 8.7):
C:\Users\flip111\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.2\bin\ghc.exe
is version 8.8.2
```

**Comment by fendor** [comment]
Theoretically, hie-wrapper does exactly that. It probably failed though to detect that it was used in a stack project.
Can you describe your project structure and how you opened the project in hie?

**Comment by flip111** [comment]
```
git clone https://github.com/haskell/cabal.git
cd cabal
code .
```

**Comment by fendor** [comment]
Do you have `cabal` installed but not ghc?
In our heuristic, existence of `cabal.project` and `cabal` is installed, indicates that the project is a cabal project, therefore we are trying to access the `ghc` version on the path, which fails. Could be more resilient.

**Comment by flip111** [comment]
It seems that cabal is installed at `C:\Users\flip111\AppData\Roaming\local\bin\cabal.exe`.

So if a project both supports cabal and stack, cabal takes precedence?

**Comment by fendor** [comment]
If cabal and stack are installed and both `cabal.project` and `stack.yaml` exist, then yes, cabal takes precedence for no reason but implementation detail. Currently, the only way to tell hie to use stack in that case is using a custom `hie.yaml` -> https://github.com/haskell/haskell-ide-engine#project-configuration

**Comment by flip111** [comment]
I think this should be the other way around because when `stack.yaml` is present people are more likely to prefer stack than cabal. People who don't like stack and use cabal often don't put a `stack.yaml` in the project.

**Comment by fendor** [comment]
If you explictly check in a `cabal.project`, we just assume it the other way around. This is just roughly a 50-50 chance to get right. I for example prefer cabal, but have stack installed for testing. For me it would be annoying the other way around. The best way would be to specify it via `hie.yaml` where the developer can specify the build-tool explictly. See https://github.com/haskell/haskell-ide-engine/issues/1516 which would solve this problem. BTW, implementation of #1516 is rather trivial right now.

**Comment by flip111** [comment]
I'm not sure what the difference is between `myproject.cabal` and `cabal.project`. But i notice that in a fresh stack project `cabal.project` is not available. So when looking at this file you could be quite right that it's a 50/50 situation.

Instead of just this message `hie-wrapper: dieVerbatim: user error (hie-wrapper: The program 'ghc' version >=7.0.1 is required but it could not be found.)` can it explicitly say that cabal and not stack was chosen to do the build?

**Comment by fendor** [comment]
the file `cabal.project` has the same rank as `stack.yaml` just for cabal. You can specify certain information that cant be expressed via a `*.cabal` file.

No, we can not do that easily because we are calling a library to give us this error (and project initialisation in general) and we dont receive the error message, it is an exception. I would rather avoid catching and then parsing it to decide how to handle it properly.

**Comment by flip111** [comment]
Can it not next to the exception itself print out some "general information" on the next line that always gets printed in case of an exception?

**Comment by fendor** [comment]
I dont know how often this information is accurate. There are many corner cases wehre additional information might be usefuk. And just dumping a ton of information to the user does not seem like a sensible solution, imo. And in this case, the error message is absolutely clear, although the reason why it is thrown is not.
Moreover, when which tool is selected is documented in https://github.com/haskell/haskell-ide-engine#project-configuration

**Comment by flip111** [comment]
Ok let's close this for now.
