### ISSUE TITLE
current "master" is branch "broken-0.35"

### ISSUE THREAD

**Issue by alanz** [alanz/vscode-hie-server#208]
I managed to mess up release 0.0.35, which simply did not work as published. You cannot roll back from the market, so I rolled forward to 0.0.36, by doing a hard reset of the master branch to tag 0.0.34, updating the version, and tagging it to force publication.

The state of master prior to this surgery is in branch "broken-0.35"

**Comment by jneira** [comment]
I've tested broken-0.35 locally and it passes the test suite but i have diff versions of node and npm than travis.
I've just triggered it in travis: https://travis-ci.org/jneira/vscode-hie-server/builds/646350457

**Comment by alanz** [comment]
Ok, I will take another look, with less time pressure this time.

**Comment by jneira** [comment]
I think we can close this one
