### ISSUE TITLE
prefer stack over cabal

### ISSUE THREAD

**Issue by LeanderK** [alanz/vscode-hie-server#213]
HIE wrapper seems to prefer cabal over stack. It would be nice if this could be configured.

**Comment by fendor** [comment]
via a language server setting or is the explicit `hie.yaml` enough?

**Comment by LeanderK** [comment]
ah yeah, hie.yaml is the right idea

**Comment by fendor** [comment]
I dont have anything against a language-server-setting, too. 
Also, there is currently no way to specify to use the cabal-helper based discovery mechanism. Relevant issue https://github.com/haskell/haskell-ide-engine/issues/1516
