### ISSUE TITLE
Version 0.0.37 stuck at type checking

### ISSUE THREAD

**Issue by Abastro** [alanz/vscode-hie-server#220]
I don't get what is causing this; I do know that it's version-specific problem, as in it only happens in 2 versions, v0.0.37 and v0.0.35
No error messages at all, output shows nothing, and it is stuck at type checking phase - as if it's doing some work, when it isn't...

What should I do to trace this problem down? Is this only specific to my local end?

**Comment by fendor** [comment]
Take a look at https://github.com/alanz/vscode-hie-server#investigating-and-reporting-problems.
Are there any logs? If yes, please provide them.

**Comment by Abastro** [comment]
Nvm, seems like it was a problem on my end. Don't know why it happened, but it works now anyway..
