### ISSUE TITLE
Extension doesn't seem to be running at all on macOS

### ISSUE THREAD

**Issue by samuela** [alanz/vscode-hie-server#221]
When I open up a `.hs` file (outside of any stack/cabal project). I'm not seeing anything happen at all. The "Extensions" log in the bottom pane doesn't seem to have any output either. I'm running on macOS 10.15.4. I installed HIE via cabal based on the instructions in the README. Not sure what could possibly be wrong since there's no error messages or anything.

Version: 1.45.0-insider
Commit: 1c36d747fbf113144d3bf82b0aa3cbd290714e38
Date: 2020-04-15T05:40:02.537Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by fendor** [comment]
Just to clarify, there are no logs? E.g. https://github.com/alanz/vscode-hie-server#investigating-and-reporting-problems
You could also attempt to execute `hie-wrapper --debug .` and link the output here.

**Comment by samuela** [comment]
@fendor Yeah, my problem is that I'm not seeing "Haskell HIE (cabal)" in the Output dropdown:
![Screen Shot 2020-04-16 at 12 01 38 PM](https://user-images.githubusercontent.com/226872/79495819-08798080-7fda-11ea-8667-557c80003f54.png)

**Comment by samuela** [comment]
Oh, and I do have "Trace: Server" set to "verbose" in the extension settings.

**Comment by fendor** [comment]
How did you try to start the extension? Open a haskell source file and installed the plugin?

**Comment by fendor** [comment]
Sorry, no idea what might have caused this.

**Comment by samuela** [comment]
Ah, so it seems that the problem is that the extension won't run unless there's a folder opened up in the "workspace". It's not enough to open a Haskell file in a new window that hasn't opened a folder yet.

**Comment by expipiplus1** [comment]
> Ah, so it seems that the problem is that the extension won't run unless there's a folder opened up in the "workspace". It's not enough to open a Haskell file in a new window that hasn't opened a folder yet.

I have actually bumped into this before, is it possible to error or warn on this? Or at the least mention in the readme perhaps.
