### ISSUE TITLE
Add a configuration option to switch easily between ghcide, hls and hie

### ISSUE THREAD

**Issue by jneira** [alanz/vscode-hie-server#222]
* A select with fixed options could work
* We can take [emacs lsp-haskell as example](https://github.com/emacs-lsp/lsp-haskell/blob/e9c306b8246e2b50bf9260f71b3d2e5334b90b30/lsp-haskell.el#L39-L49)
* We should choose the initial default value (probably hie for now)
  * We could switch to hls at the right time
* Maybe the rest of params would need a redesign
* We can remove the actual shell scripts:
  * https://github.com/alanz/vscode-hie-server/blob/master/hie-vscode.bat
  * https://github.com/alanz/vscode-hie-server/blob/master/hie-vscode.sh

**Comment by alanz** [comment]
I am changing the startup config options to be

```json
        "languageServerHaskell.hieVariant": {
          "scope": "resource",
          "type": [
            "haskell-ide-engine",
            "haskell-language-server",
            "ghcide"
          ],
          "default": "haskell-ide-engine",
          "description": "Which hasell language server to use."
        },
        "languageServerHaskell.hieExecutablePath": {
          "scope": "resource",
          "type": "string",
          "default": "",
          "description": "Set the path to your hie executable, if it's not already on your $PATH. Works with ~, ${HOME} and ${workspaceFolder}."
        },
        "languageServerHaskell.enableHIE": {
          "scope": "resource",
          "type": "boolean",
          "default": true,
          "description": "Enable/disable HIE (useful for multi-root workspaces)."
        }
      }
    },
```

Use the selected variant, mapping to `hie-wrapper`, `haskell-language-server-wrapper` or `ghcide`, unless the `hieExecutablePath` is set, in which case use that.
