### ISSUE TITLE
Update documentation for wrappers

### ISSUE THREAD

**Issue by tjdett** [alanz/vscode-hie-server#224]
Wrappers with `languageServerHaskell.useCustomHieWrapperPath` were removed in 0.0.40, but unfortunately `README.md` still specifies using them instead of `languageServerHaskell.hieExecutablePath`.

This is confusing for anybody with a custom wrapper, as the upgrade path from 0.0.39 is not immediately obvious.

Unfortunately this may not be a quick find-and-replace, as the section "Using multi-root workspaces" does not appear to have a straight-forward alternative.

**Comment by jneira** [comment]
@tjdett thanks for note it, docs has been updated to remove the wrapper related options with #227
