### ISSUE TITLE
completion does not work

### ISSUE THREAD

**Issue by markxnelson** [alanz/vscode-hie-server#231]
Code completion does not work at all.  I just get a box that says 'Loading...' - see the image below for an example.

Software versions:
VSCode: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-7629-generic
Haskell Language Server 0.0.40

![Screenshot from 2020-05-23 22-15-42](https://user-images.githubusercontent.com/6345393/82744211-48ebbd00-9d43-11ea-8fef-b1c38232ff9e.png)

Please do let me know if additional information/logs/config files are needed - I am very new to Haskell, so I am not sure what might be needed.

I installed using stack as in the documentation, including trying hie-8.6.5.

**Comment by markxnelson** [comment]
Not sure if this is useful, or what it means, but after restarting code, I get this error:

![Screenshot from 2020-05-23 22-25-14](https://user-images.githubusercontent.com/6345393/82744282-4e95d280-9d44-11ea-95ac-7177a853d361.png)

**Comment by markxnelson** [comment]
Oh, I think I found the problem, I was trying to turn on tracing like it says at the bottom of the readme, and I noticed haskelly was installed too.  I disabled it, and now completion works. 
I will leave this issue open in case you want to update the doc to mention this. Otherwise feel free to close, and thank you!

**Comment by jneira** [comment]
@markxnelson Thanks for reporting it (and find the problem 😄 )
Agree maybe it deserves a note in docs, although not sure where.
