### ISSUE TITLE
Update default Hie Variant to haskell-ide-engine or haskell-language-server

### ISSUE THREAD

**Issue by andrewguy9** [alanz/vscode-hie-server#237]
Per discussion https://github.com/haskell/haskell-ide-engine/issues/1520.
Updating the default could help users get a better experience with more maintained variants. 

Stack/Cabal installation instructions would also need to be updated.

**Comment by jneira** [comment]
Hi, thanks, we were waiting to have a haskell-language-server version stable and reliable enough to make the switch.
As "enough stable and reliable" is somewhat ambiguous maybe it is already the time to do it.

**Comment by andrewguy9** [comment]
I'm certainly having a better time of it. The `haskell-ide-engine` had been hanging and crashing on the default `stack new` project template.

**Comment by bubba** [comment]
I would propose to do this as a part of #236, as the "magical" installation of haskell-language-server part would be pretty pointless if haskell-language-server was not selected as the default

**Comment by fendor** [comment]
I agree, while HLS will have some starting problems, e.g. you almost always have to write a `hie.yaml`, it is already more stable than HIE (including auto-reload on dependency changes) and faster.

It would be important to have the ultimate guide to write your own `hie.yaml`. Also, a way to generate it via HLS/ghcide.
