### ISSUE TITLE
Adding link to MarketPlace in GitHub header

### ISSUE THREAD

**Issue by Tehnix** [alanz/vscode-hie-server#26]
cc @alanz 

I wanted to hear if you could possibly add https://marketplace.visualstudio.com/items?itemName=alanz.vscode-hie-server to the header of the GitHub info (next to the description). While I have push access, it seems setting settings (understandably) is still limited :)

**Comment by alanz** [comment]
Is this still needed, given the rework you have done to the main page?

**Comment by Tehnix** [comment]
I think it still makes sense, yeah. The readme itself doesn’t mention the market place, because it’s displayed on the marketplace page also. On the market place though, we link to github in the side, so thought it’d be nice to go full circle with the GitHub description link going to the market place :)

**Comment by alanz** [comment]
Ok, do you want to make a PR, and then we release?

Alan

**Comment by Tehnix** [comment]
Ah, the link in the description is a github thing, I actually can’t PR it. Like, on the front page of the repo you can edit the description, and in the same place you can also add a link.

I think it’s admin privilege thing I think 🤔

**Comment by alanz** [comment]
Ok, done it. Sorry, should have actually paid attention.
