### ISSUE TITLE
Add tslint?

### ISSUE THREAD

**Issue by halhenke** [alanz/vscode-hie-server#29]
Have been mucking around with adding an option to show the output of the `Show Type` command on hover (much like in the `ide-haskell` plugin for Atom). Never really mucked around with Typescript or VSCode API but have missed having eslint in terms of catching some other obvious errors (shadowing variable names etc) and providing consistency. To that end I think it might be nice to add [tslint](https://palantir.github.io/tslint/) to the project. It definitely helped track down some errors while i was refactoring a bit of code.

If this sounds good I would be happy to submit a PR?

**Comment by AlexeyRaga** [comment]
I think it'll be super useful.

**Comment by Tehnix** [comment]
That sounds great, yeah :)

**Comment by alanz** [comment]
@halhenke Please submit a PR
