### ISSUE TITLE
Hovering over comments and library functions spams errors

### ISSUE THREAD

**Issue by AlexeyRaga** [alanz/vscode-hie-server#3]
On MacOS:

- Press `Cmd`
- Move cursor over some comments, type definitions or library functions.

This kind of error messages appears in an output pane: 
![image](https://user-images.githubusercontent.com/1394391/28969084-707eccd0-7966-11e7-83e6-6deb25992ac6.png)

**Comment by wz1000** [comment]
vscode calls findDefinition on every position you hover over when pressing `Cmd`. Currently, we don't have a better way to report this error. `ShowMessage` is even more intrusive.

**Comment by alanz** [comment]
Can we not return some kind of null result?

**Comment by alanz** [comment]
Send an empty list

**Comment by wz1000** [comment]
@AlexeyRaga can you confirm that this issue is solved by https://github.com/haskell/haskell-ide-engine/pull/298 ?

**Comment by AlexeyRaga** [comment]
I haven't seen this issue for a while now
