### ISSUE TITLE
Add setting for multiple hie versions

### ISSUE THREAD

**Issue by alanz** [alanz/vscode-hie-server#31]
The `hie` executable is built based on a particular GHC version, and as it uses the GHC API and loads the project using it, the `hie` GHC and project GHC must match.

`hie` can now be built for GHC 8.0.2, 8.2.1 and 8.2.2.

Provide a client-side setting to choose a specific `hie` executable for a project.

**Comment by nponeccop** [comment]
Do you want it to be similar to `hlintOn` in https://github.com/alanz/vscode-hie-server/blob/master/package.json#L79 ? Note that we can define enums in JSON schema.

**Comment by Tehnix** [comment]
I was wondering, as to make as little coupling to any editor, would it make sense for `hie` itself actually be a wrapper for `hie-x.y.z`, which is tied to the GHC version it was built for? Then `hie` would do its best to hit the right GHC version and then tunnel everything to that binary, while the editor configuration would then be for forcing a particular version? 🤔

My goal is in general to pack as much of the functionality in hie itself, so we don't loose any of the advantage we are seeing of editor plugins for hie being little more than "how to start the executable in with this particular LSP plugin".

**Comment by alanz** [comment]
I see this eventually being handled on the server side. But in the interim the low hanging fruit is to do it in the client, like the hlint on/off setting

**Comment by nponeccop** [comment]
I'll take a look

**Comment by stellarhoof** [comment]
Wouldn't providing a package and requiring it to be built locally with `stack` solve this issue? If it's included in the stack snapshots it'd choose the right package automatically. Is it because we shouldn't assume someone uses stack?

**Comment by nponeccop** [comment]
I don't see how inclusion in stack snapshot helps us. And there are custom/local snapshots.

**Comment by alanz** [comment]
Closed (as good enough) via https://github.com/haskell/haskell-ide-engine/pull/447 and https://github.com/alanz/vscode-hie-server/pull/41
