### ISSUE TITLE
Applying HLint Suggestions does not work properly

### ISSUE THREAD

**Issue by soylens** [alanz/vscode-hie-server#33]
Sometimes it doesnt delete the old code and just append everything after the entire code block
```haskell
--getInts = fmap (map read . words) getLine
getInts = fmap ((map read). words) getLine
```
turns into
```haskell
--getInts = fmap (map read . words) getLine
getInts = fmap ((map read). words) getLine--getInts = fmap (map read . words) getLine

getInts = fmap (map read. words) getLine
```
and another one:
```haskell
main :: IO ()
countFac :: Int -> Int -> Int

main = do
    getLine
    a_temp <- getLine
    let a = map read $ words a_temp :: [Int]
    b_temp <- getLine
    let b = map read $ words b_temp :: [Int]
    let l = foldl lcm (head a) (tail a) --THIS LINE IS TO BE REPLACED WITH foldl1
    let g = foldl1 gcd b
    let s = g `div` l
    if s * l /= g
        then do
            print 0
            return ()
        else do
    print (countFac s 1)
    return ()

countFac n c
    | c > n `div` 2 = 1
    | n `div` c * c == n = 1 + countFac n (c+1)
    | otherwise = countFac n (c+1)
```
turns into
```haskell
main :: IO ()
countFac :: Int -> Int -> Int

main = do ---THE getLine HERE IS MISSING
    a_temp <- getLine
    let a = map read $ words a_temp :: [Int]
    b_temp <- getLine
    let b = map read $ words b_temp :: [Int]
    let l = foldl lcm (head a) (tail a) --IT'S STILL HERE
    let g = foldl1 gcd b
    let s = g `div` l
    if s * l /= g
        then do
            print 0
            return ()
        else do
    let l = foldl1 lcm a -- IT GOT APPENDED HERE
countFac n c
    | c > n `div` 2 = 1
    | n `div` c * c == n = 1 + countFac n (c+1)
    | otherwise = countFac n (c+1)
```
I'm using Caps so that it would be easier to locate them

**Comment by nponeccop** [comment]
Interestingly if I use `hlint --refact` I get the correct output. Here is the diff:

```diff
diff --git a/bar.hs b/bar.hs
index 8a402a0..5c04dd0 100644
--- a/bar.hs
+++ b/bar.hs
@@ -7,7 +7,7 @@ main = do
     let a = map read $ words a_temp :: [Int]
     b_temp <- getLine
     let b = map read $ words b_temp :: [Int]
-    let l = foldl lcm (head a) (tail a) --THIS LINE IS TO BE REPLACED WITH foldl1
+    let l = foldl1 lcm a --THIS LINE IS TO BE REPLACED WITH foldl1
     let g = foldl1 gcd b
     let s = g `div` l
     if s * l /= g
```
I installed hlint and refact using `stack.yaml`, so they are of exactly the same version HIE gets for GHC 8.0.2.

The steps to reproduce are:

- go to hie build folder
- run `stack install hlint refact`, appending `--stack-yaml=` if necessary
- if you did it correct then only a few things get rebuilt as we basically add 2 executable targets
- create bar.hs with the second example from this report
- run `git add bar.hs` so it's easy to get a diff later on
- run  `hlint  bar.hs --refactor --refactor-options="--inplace"`
- run `git diff bar.hs`
- unstage `bar.hs` by `git reset HEAD bar.hs` and delete it

**Comment by soylens** [comment]
So you failed with the VS code addon?
BTW by me it said hlint.exe:cound not find refactor
So installed apply-refact and hlint works yet it still doesnt work with the HIE plugin.
Im not sure if it's your problem or HIE's

**Comment by nponeccop** [comment]
I didn't try VS code. I only checked bare `hlint --refactor` command line

**Comment by nponeccop** [comment]
You should state why the bug is closed (for future readers)

**Comment by soylens** [comment]
Cuz this is not a problem on this side
