### ISSUE TITLE
HIE confused about project modules

### ISSUE THREAD

**Issue by jchia** [alanz/vscode-hie-server#38]
I have a [simple project](https://github.com/jchia/hie-bug) demonstrating what appears to be a bug.

The project has 2 modules `Lib1` and `Lib2`, the latter importing the former. Upon opening `Lib2.hs` in vscode, I get this error popup:
```
Got error while processing diagnostics: These modules are needed for compilation but not listed in your .cabal file's other-modules: Lib1
```

If I dismiss it, I can continue working on the file, but it reappears whenever I make a change.

I don't know whether this is a bug with the frontend (vscode-hie-server) or backend (haskell-ide-engine). I don't know of a way to elicit more helpful diagnostics. All I can see is that some `hie --lsp` process is running, apparently automatically spawned from vscode, and I can't examine its stdout or make it log somewhere. So, the other issue is the apparent lack of facilities in the vscode extension to expose diagnostics and logging to enable people to make more useful bug reports. Should I file an issue for that?

The `hie` I'm using is the latest from HEAD but with stack.yaml changed to use nightly-2017-12-27 and `allower-newer: true` so that I can use it with GHC 8.2.2.

**Comment by nponeccop** [comment]
This is a duplicate of https://github.com/haskell/haskell-ide-engine/issues/391 and https://github.com/alanz/vscode-hie-server/issues/36

**Comment by jchia** [comment]
Indeed.
