### ISSUE TITLE
Add an option for only checking on file save

### ISSUE THREAD

**Issue by sgronblo** [alanz/vscode-hie-server#39]
Currently this plugin seems to rechecking the file on each edit. This uses quite a lot of CPU and can adversely affect your laptop's battery life.

It would be nice if there was an option for this plugin to only check for errors in a file when the file is saved.

**Comment by Tehnix** [comment]
Hmm, I currently know of no API that sets this, but I could imagine it should happen from the LanguageClient side (as in, don't send the edit events).

I'll try to look into it. Do you by chance know any existing extensions that does this? Then I could dig around, to see how they are doing it :)
