### ISSUE TITLE
Hoogle version conflict leads to crash of type information feature

### ISSUE THREAD

**Issue by mitutee** [alanz/vscode-hie-server#42]
There is some mismatch of hoogle versoins at my machine, and that leads to crash of type info popups.
When I open project with vs code and hoover over 3rd party types, popups work fine. But when I hoover over my type, the error happens, and I get `Loading..` popup even for types that worked normally before that error.

## Expected Behavior
If something goes wrong with one hoogle database, it is still possible to see type information provided by valid ones.

## Actual Behavior
After I hoover over my function, type info feature crashes, and I cant see info about any function. It doesnt work even with types that were OK before the crash. Extension output:

```
hie: The Hoogle file /home/mitutee/Programming/my/project-management-tool/server/.stack-work/hoogle/x86_64-linux/lts-10.3/8.2.2/database.hoo is the wrong version or format.
Expected: HOOGLE-5.0.16
Got     : HOOGLE-5.0.14
CallStack (from HasCallStack):
  error, called at src/General/Store.hs:177:13 in hoogle-5.0.16-9nJOEzrw9JECpz50DooZQ3:General.Store
CallStack (from HasCallStack):
  error, called at src/General/Util.hs:235:66 in hoogle-5.0.16-9nJOEzrw9JECpz50DooZQ3:General.Util
```

**Comment by Tehnix** [comment]
To generate the local hoogle database, check out https://github.com/haskell/haskell-ide-engine#docs-on-hovercompletion. Specifically I think you need to run,

```
$ cd haskell-ide-engine
$ stack --stack-yaml=<stack.yaml you used to build hie> exec hoogle generate
```

Let me know if this doesn't resolve your problem, and I'll reopen this issue.
