### ISSUE TITLE
Support for Test Suites?

### ISSUE THREAD

**Issue by mtesseract** [alanz/vscode-hie-server#43]
Hi,

I am currently testing the VSCode extension for HIE. So far, my test project is looking good in VSCode/HIE, but the included test suite does not seem to be "working" out of the box: Its dependencies do not seem to be "in scope". The package.yaml contains the following:

```
tests:
[…]
    dependencies:
[…]
    - test-framework
    - test-framework-hunit
```
ghcmod says:

```
Could not find module 'Test.Framework' Use -v to see a list of the files searched for.
```

along with some other modules, which are imported by the test module.

When I use Intero in Emacs, I use `M-x intero-targets` to specify that I want both "targets" — the main library plus the test suite — loaded. Is something similar required for VSCode/HIE?

Thanks!
Moritz

**Comment by Tehnix** [comment]
In case you don't get any responses here, I think this might be better posted on https://github.com/haskell/haskell-ide-engine, which I think has more traffic. 

Not at all to dismiss your problem, but the main work is happening in the language server itself, and not so much in the clients (like VSCode is).

**Comment by Tehnix** [comment]
The test dependencies need to be built after adding them. It should by default pick both, else I would open a ticket on [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine). 

Closing this to clean up, let me know if it should be reopened.
