### ISSUE TITLE
No hoogle db found. Check the README for instructions to generate one

### ISSUE THREAD

**Issue by wiz** [alanz/vscode-hie-server#44]
But there are no instructions in readme... :confused:

**Comment by Tehnix** [comment]
I think it meant the HIE readme, but that is obviously not clear :)

If I remember correctly you need `Hoogle 5.0.16`, which can mean a upgrade via e.g. stack install and a newer resolver. And then follow https://github.com/haskell/haskell-ide-engine#hoogle-docs-on-hover for more information about generating.
