### ISSUE TITLE
Doesn't start hie in project root

### ISSUE THREAD

**Issue by dhruvrajvanshi** [alanz/vscode-hie-server#45]
I am using this extension for a stack project. Autocomplete wasn't working so I started looking into it.

In the output window for the extension, I saw this

```
Launching HIE for project located at /home/dhruv
```

This is my home directory. Is this expected behaviour? I expected it to start HIE with the project root.

Now I think about it, HIE might have changed its default behaviour from picking up current directory as project to home directory.

Anyway, I changed this line in ~/.vscode/extensions/alanz.vscode-hie-server-0.0.8

```
# Run directly
hie --lsp $@
```

to

```
hie --lsp -r . $@
```

And it started working again.

Here's the output of `hie --version` on my machine.

```
Version 0.1.0.0, Git revision 4f2173963b14cb7603bc0c1ce731dc07ac1b7feb (1183 commits) x86_64 ghc-8.2.2
```

**Comment by Tehnix** [comment]
The extension sets the root folder as the workspaceFolder, so this should not happen anymore. We can reopen this issue if you are still experiencing problems :)
