### ISSUE TITLE
Command to restart hie

### ISSUE THREAD

**Issue by LukaHorvat** [alanz/vscode-hie-server#46]
Due to some reason (probably all the way down in the GHC API) pretty much every Haskell IDE tool consumes a ton of memory and the amount usually increases with use. I currently solve this by monitoring memory usage and restarting VS Code when I see it's taking up too much. The problem is that this kills terminal sessions in the editor.

I'd like to be able to restart just the hie backend.

**Comment by Tehnix** [comment]
I'd very much like this too, but haven't been able to find anything in the VSCode LSP that would allow that. If anyone can point me to somewhere in the documentation where it says something about stopping and starting the server again, I'd be fine with giving it a stab :)

**Comment by alanz** [comment]
Simplest is just to kill the server, `vscode` is quite good at restarting if it disappears.

And we `do` get the process id back. Because having recently got this in emacs (https://github.com/emacs-lsp/lsp-mode/pull/290, for me anyway), I can testify to its usefulness.

**Comment by andrewufrank** [comment]
the ability to restart the HIE would help when the diagnostics are not updated automatically. perhaps simpler but still very helpful would be a way to see which `pid` the `HIE` thread has (the one for this `vs code terminal` -- there are typically several ones)

**Comment by Swoorup** [comment]
👍 for this. I would like restart feature especially in cases when I add new stack packages and HIE isn't able to update its internal definition. A restart would solve this for now.

**Comment by jneira** [comment]
@Swoorup Could you use the general command "Reload Window" (by default bint to `ctrl + R`) as workaround?

**Comment by Swoorup** [comment]
@jneira Can confirm that works as a workaround. 

Will use that for now. Just an FYI, there are other LanguageServer that has this feature as well. 

![image](https://user-images.githubusercontent.com/3408009/72308053-19131580-36d0-11ea-8ed5-ab423d048bcf.png)
