### ISSUE TITLE
Comment a selection

### ISSUE THREAD

**Issue by flip111** [alanz/vscode-hie-server#487]
When i press `CTRL + /` vscode puts `--` in front of the line and comments the whole line, cool !

Would be awesome as well when i make a selection that it would quotes around that part. When using the same hotkey as commenting a line this could only work within a single line, otherwise selecting multiple lines and quoting them would break. For this reason another hotkey could be used.

```haskell
myValue = 1 + 2 + 3 + 4
```

Selected with the mouse: `+ 2 + 3`

Result after commenting selection
```haskell
myValue = 1 {- + 2 + 3 -} + 4
```
Prefix added `{- `, suffix added ` -}`

**Comment by jneira** [comment]
@flip111 hi! thanks for the suggestion. Actually i have been able to comment a selection, using the command `Toggle block comment``(ALT + `):

![imagen](https://user-images.githubusercontent.com/54035/138350527-ce2087ee-d835-4460-af9a-e49e33d4a697.png)
