### ISSUE TITLE
Support typescript-2.7.2

### ISSUE THREAD

**Issue by ndmitchell** [alanz/vscode-hie-server#50]
Using the latest git, when I do `npm run compile` (which I believe `vsce package` does), I get the error:

```
C:\Neil\vscode-hie-server>npm run compile

> vscode-hie-server@0.0.8 compile C:\Neil\vscode-hie-server
> tsc -p ./

src/commands/showType.ts(116,5): error TS2322: Type '[Disposable, OutputChannel]' is not assignable to type '[Disposable]'.
  Types of property 'length' are incompatible.
    Type '2' is not assignable to type '1'.
```

I am using `tsc --version == 2.7.2` on Windows.

**Comment by halhenke** [comment]
Yeah I just ran `npm run compile` this on OSX & I didnt get an error

however I do get the same error when I open that file in VSCode itself. 
The difference being that VSCode currently uses typescript version 2.72 whereas we are locked to version 2.62. If I run `tsc -p ./` with 2.72 I get the same error

So we should update typescript dependencies to try & keep things in line though its not an urgent issue. 

I’m not sure if your npm is not using the local typescript version or if it has ignored the lockfile - perhaps its a Windows thing?

**Comment by ndmitchell** [comment]
Ah, I think I got an error message from `npm` which caused me to think typing `npm update` would help - which altered the lock file and broke everything. So it now works for me, and I'll adjust the ticket.
