### ISSUE TITLE
A newline is added at each save

### ISSUE THREAD

**Issue by marmistrz** [alanz/vscode-hie-server#57]
This results in a huge amount of trailing newlines.

**Comment by otbe** [comment]
In addition to this I get sometimes a strange behavior on removing or adding some lines of code. For example: after insertign the type definition of a function via command it adds the function definition with each save action. Its not always the case.

Maybe this is related to this...

**Comment by jneira** [comment]
I cant reproduce it anymore with latest hie. @marmistrz could you try again?
