### ISSUE TITLE
Warnings for non-exhaustive pattern matches?

### ISSUE THREAD

**Issue by mgreenbe** [alanz/vscode-hie-server#58]
I've noticed that I'm not getting warnings for non-exhaustive pattern matches. Here's an example:
```
eval (Plus, ns) = sum ns
eval (Minus, n:ns) = n - sum ns -- sum [] == 0
eval (Times, ns) = product ns
eval (Divide, n:ns) = n / product ns
```
(The cases `(Minus, [])` and `(Divide, [])` aren't handled.)

Stack notices this when I build with the `--pedantic` flag:

```
/home/mgreenbe/my-project/app/Main.hs:33:5: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘eval’:
        Patterns not matched:
            (Minus, [])
            (Divide, [])
```
Should the linter catch this?

Also, should I file this against a different repo, the linter or the HIE server itself?

**Comment by ElvishJerricco** [comment]
I believe HIE will just use the GHC options in your cabal file. I recommend adding `-Wall` to your `ghc-options`.

**Comment by mgreenbe** [comment]
@ElvishJerricco Worked, thanks! (Stack actually seemed happier with me putting it in the `package.yaml` file, but I'm sure that's specific to my setup.)
