### ISSUE TITLE
HIE seems to be not working although the logs says it's working

### ISSUE THREAD

**Issue by sharno** [alanz/vscode-hie-server#62]
I just installed HIE by cloning its repo and stack install it. I also put the path for starting HIE in the custom wrapper settings:
```
"languageServerHaskell.useCustomHieWrapper": true,
"languageServerHaskell.useCustomHieWrapperPath": "~/.local/bin/hie",
```

Opening a Haskell file shows in the output in VSCode that HIE started:
```
2018-04-05 08:37:18.748998 [ThreadId 4] - run entered for HIE Version 0.1.0.0, Git revision f707b3d12f8b54d7ebf9c32363b2b1a8bd04686d (1262 commits) x86_64 ghc-8.2.2
2018-04-05 08:37:18.752067 [ThreadId 4] - Current directory:/Users/sharno/projects/rogue
```

But all I get in VSCode is just syntax highlighting (from Haskell Syntax Highlighting extension) but nothing from Haskell Language Server extension, (no types on hover or autocomplete or anything, as if it's not there)
Did I miss something in configuration?

**Comment by Tehnix** [comment]
Some questions that might help debugging this:

- In the `Output` tab, do you see a `Haskell HIE (..)` in the dropdown?
- What is the contents of your wrapper at `"~/.local/bin/hie"`?
- If you, via the command palette (`CMD + SHIFT + p`) open `Developer: Toggle Developer Tools`, do you see any meaningful output?

**Comment by sharno** [comment]
@Tehnix 
- yeah, the output actually shows only in this choice from the dropdown
- this is actually the binary of hie directly, as it installed there and this path isn't in my PATH environment variable, changing the path seemed not to work as I'm using Fish and the extension didn't see the PATH change so I thought putting the path HIE binary in the wrapper should work (hope that's not the issue)
- There's nothing in the console of Developer Tools

**Comment by Tehnix** [comment]
Ah, then I see your problem. HIE needs to be started with arguments, but if you use the custom wrapper, it leaves everything to the user.

I often use this one,

```bash
#!/usr/bin/env bash
DEBUG=1
indent=""
function debug {
  if [[ $DEBUG == 1 ]]; then
    echo "$indent$@" >> /tmp/hie-custom-wrapper.log
  fi
}

curDir=`pwd`
debug "Launching HIE for project located at $curDir"
indent="  "

# Launch the hie for the LTS compiler (assuming built with --copy-compiler-tools).
debug `stack exec -- which hie`
stack exec -- hie --lsp --debug -l /tmp/hie.log
```

Which for stack based project finds the one I installed (and some additional logging). To tailor it to you, the following should work,

```bash
#!/usr/bin/env bash
$HOME/.local/bin/hie --lsp
```

Basically, for the custom wrapper, you need to supply at least `--lsp` in whatever script you set as the custom wrapper. It's not meant to point to the executable directly. That said, we should add a way to specify a custom path in the settings. If you can bear with me, I can do that quickly :)

**Comment by sharno** [comment]
@Tehnix Oh I would deeply appreciate that. Thanks a lot for bearing with me and adding such an option 😄

**Comment by sharno** [comment]
That was fast 😄 . Thanks a lot!
