### ISSUE TITLE
GHCup can't easily be told not to install e.g. Stack at initial setup

### ISSUE THREAD

**Issue by georgefst** [alanz/vscode-hie-server#622]
Since #547, at initial setup, GHCup offers to install HLS, Cabal and Stack. But there's no way to specify that we only desire a subset of these.

This can be annoying e.g. for those of us who literally never use Stack, and have limited network bandwidth or disk space.

**Comment by georgefst** [comment]
Aha fair enough, thanks, that's useful. But it could be more discoverable. Everything else works so smoothly that people are mostly probably not going to look at the documentation.

The popup isn't the right place for complex configuration, but maybe there should just be a subtitle below the "Need to download..." heading like "see `Haskell: Toolchain` setting to configure this"?

![image](https://user-images.githubusercontent.com/12991097/173363839-58a93997-1890-477b-bf7c-3ac66838d6e5.png)

**Comment by hasufell** [comment]
> Everything else works so smoothly that people are mostly probably not going to look at the documentation.

Well, I'm not sure that's fixable 😄

The popups really can't convey all of the information, but feel free to create a PR and we can discuss the specific suggestion.

**Comment by georgefst** [comment]
Ok, I'll look in to implementing it!

To be clear, my personal experience of updating to the latest version of the extension was "oh I don't want stack, ghcup is trying to do too much, I'll just do it the old-fashioned way". I hope to make it clearer for other people that there is more flexibility.

**Comment by hasufell** [comment]
The main problem here is about discovering ahead of time whether you're using a cabal or stack cradle.

This could be something the `haskell-language-server-wrapper` implements as a subcommand, so that the extension can query it before running installation. 

But I'm not sure how ambiguous that would be for non-standard projects not having a cradle file.
