### ISSUE TITLE
HIE stops working when doing a `stack build` OSX

### ISSUE THREAD

**Issue by YoEight** [alanz/vscode-hie-server#69]
Greetings,

First, I'm very sorry for not being able to come up with a more descriptive title, but it is what I'm experiencing.

HIE is working (all the types information and hoogle documentation) but for an unknown reason, after some time, it stops and keeps displaying `Loading` message when I'm hovering a symbol. That behavior persists even when I restart VS Code, or Uninstall / Install HIE.

It does this behavior for all the projects I have. I hardly believe it's because of a time constraint of course. It has to come from my dev workflow but hard to found out as no error message shows up.

Thanks for your time.

env:
- OSX High Sierra
- HIE: 2.4.0
- Code: 1.22.2
- GHC: 8.2.2
- Stack: 1.6.5

**Comment by YoEight** [comment]
I found why it does no longer working. HIE stops working when I do a `stack build` in my project directory. In order to bring HIE back. I have to `stack hoogle` in my project directory and then restart VS Code. I'm editing the title accordingly.

**Comment by YoEight** [comment]
Note that HIE stops to work also when you edit your `stack.yaml` file. To set it back, quit VS Code, `stack hoogle` in your project, launch VS Code and everything is working again.

**Comment by AlexeyRaga** [comment]
Strange, I work on OSX and change my `stack.yaml` very often and I haven't seen this problem yet.
Which resolver do you use?

**Comment by YoEight** [comment]
Is there a way to provide you some application log? Will probably more helpful that lame description of the problem 😄

**Comment by marianban** [comment]
I had a similar issue on OSX with displaying `Loading` message when hovering a symbol. What worked for me was to use a hie wrapper `"languageServerHaskell.useHieWrapper": true`

**Comment by Tehnix** [comment]
This would indicate to me that the hie it catches on the system is built with a different GHC version than the one you are using. The [HIE wrapper](https://github.com/alanz/vscode-hie-server/blob/master/hie-wrapper.sh#L29) will try its best to find the right executable (i.e. if it detects GHC version 8.2.2, it'll look for a `hie-8.2.2`, falling back on `hie-8.2` and finally just plain `hie`).

This will work if you have built hie with `make build` (side-note, support for GHC 8.4.4 just landed!).

**Comment by jneira** [comment]
hie does not support ghc-8.2.2 anymore so i would test with a supported ghc version and latest hie. @YoEight feel free to reopen if you continue expereincing this
