### ISSUE TITLE
"languageServerHaskell.trace.server": "verbose" setting does not seem to work

### ISSUE THREAD

**Issue by nickolay** [alanz/vscode-hie-server#77]
As I understand, adding `"languageServerHaskell.trace.server": "verbose"` to the user settings in VSCode is supposed to make a new drop-down option available in the `View -> Output` pane, which displays the communication happening between VSCode and the `hie` server.

However it appears broken: the option doesn't appear for me. (*update:* it also may appear, but only say `"Using hoogle db at: /Users/nickolay/.hoogle/default-haskell-5.0.17.hoo"` instead of listing the detailed messages exchanged.)

Judging from [this](https://github.com/Microsoft/vscode-languageserver-node/issues/39) and the [most recent version of that code](https://github.com/Microsoft/vscode-languageserver-node/blob/498a95cc386a102ce0e59375ddd42543462cd3a1/client/src/client.ts#L2831), the setting inspected is `${clientId}.trace.server`

If I change the first parameter [here](https://github.com/alanz/vscode-hie-server/blame/3817e587aed07e10195f766d76765f6fc3350130/src/extension.ts#L188) to `new LanguageClient("languageServerHaskell",` I can see the "Haskell HIE (...)" option.

BTW: why not advertise this setting more (maybe add a troubleshooting section of the README)?

**Comment by jneira** [comment]
The loggins system has changed a lot in the meanwhile: @nickolay could you give a try with latest master?
