### ISSUE TITLE
Type errors are shown only from /var/private, but not in source file

### ISSUE THREAD

**Issue by Znack** [alanz/vscode-hie-server#80]
When I do some type errors in source file in VSCode, those are not shown in the Editor, although I can see its in Problems pane:
![image](https://user-images.githubusercontent.com/2928964/39695168-e2b60558-5213-11e8-9cc5-10eb0e9604bc.png)

Please notice I have named not existing function `tableWithSelectors1SHOULDWARNHERE` although there is no warn in Editor, but I can see a lot of files from `/var/private` in Problems on the right of the screen.

I tried it with both GHC-8.2 and GHC-8.4, system is Mac OS High Sierra, I have reinstalled hie about 5 times and no success. I just do `git clone ... --recursive`, than one time I tried to checkout to `hie-0.1.0.0` with no success, tried to use directly master, no success.

**Comment by OnlyMyRailgun** [comment]
The same problem!!!

**Comment by nrskt** [comment]
@Znack @OnlyMyRailgun 

This problem may be similar to this problem. 
(https://github.com/haskell/haskell-ide-engine/issues/551)

If you can provide a debug log as in this https://github.com/haskell/haskell-ide-engine/issues/551#issuecomment-387434187, it may lead to problem solving.

**Comment by Znack** [comment]
@nrskt @OnlyMyRailgun Yesterday I have tried `af5f4fae784c32c541f91982a9f37848f3367b25` and it also works

**Comment by Znack** [comment]
I can confirm that everything works great in the last master, thank you very much for a such quick reply and fix :)
