### ISSUE TITLE
On windows, cannot start hie unless languageServerHaskell.trace.server is set

### ISSUE THREAD

**Issue by alanz** [alanz/vscode-hie-server#90]
The default ("off") value inserts an option set of `['']`, which works on linux but not windows.

Help requested from typescripters, that should be `[]`, but ts complains about not knowing the type. How do I cast it?

**Comment by Tehnix** [comment]
Ah, if you do `let debugArgs: string[] = [];`, it should be okay :) Unfortunately, typescripts inference is not that strong yet.
