### ISSUE TITLE
command 'applyrefact:applyOne' already exists

### ISSUE THREAD

**Issue by CaptJakk** [alanz/vscode-hie-server#92]
on a fresh open of a project I get the error above. Any idea what might cause that? Any other information you would need. It's tough to put together a solid repro report, but I'd be willing to work to get any additional info. I just don't know what that error means.

**Comment by alanz** [comment]
It should be fixed with current hie master, fixed by https://github.com/haskell/haskell-ide-engine/pull/629 and https://github.com/haskell/haskell-ide-engine/pull/632

**Comment by CaptJakk** [comment]
So no need to upgrade the extension, just the backend?

**Comment by alanz** [comment]
yes

**Comment by jneira** [comment]
This should be fixed, @CaptJakk feel free to reopen if you continue experiencing it
