### ISSUE TITLE
Windows 10, VS Code, useHieWrapper setting not honoured

### ISSUE THREAD

**Issue by mpilgrem** [alanz/vscode-hie-server#97]
As described at https://github.com/haskell/haskell-ide-engine/issues/670:

The documented user setting `"languageServerHaskell.useHieWrapper": true,` is not honoured, but

````
"languageServerHaskell.useHieWrapper": false,
"languageServerHaskell.hieExecutablePath": "hie-wrapper",
````
is a work-around.

**Comment by adicirstei** [comment]
👍

**Comment by alanz** [comment]
As of version 0.0.21 the hie-wrapper is always used, on all platforms, so the `languageServerHaskell.useHieWrapper` setting is no longer present nor needed.

**Comment by nwolverson** [comment]
Same issue as @mpilgrem , `languageServerHaskell.useHieWrapper` setting is gone but I see a message 

```
[Warn  - 07:49:05] Mismatching GHC versions: Project is 8.2.2, HIE is 8.4.3
You may want to use hie-wrapper. Check the README for more information
```

Adding the `"languageServerHaskell.hieExecutablePath": "hie-wrapper"` line and things work again.

**Comment by jneira** [comment]
`languageServerHaskell.useHieWrapper` was restored and it works as intended so i think we can close
